package grpc

import (
	"fmt"
	"log"
	"net"

	"github.com/ioanzicu/microservices-proto/golang/order"
	"github.com/ioanzicu/microservices/order/config"
	"github.com/ioanzicu/microservices/order/internal/ports"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

type Adapter struct {
	api                            ports.APIPort
	port                           int // port to serve gRPC on
	order.UnimplementedOrderServer     // forward compatibility support
}

func NewAdapter(api ports.APIPort, port int) *Adapter {
	return &Adapter{api: api, port: port}
}

func (a Adapter) Run() {
	var err error

	listen, err := net.Listen("tcp", fmt.Sprintf(":%d", a.port))
	if err != nil {
		log.Fatalf("failed to listen on port %d, error: %v", a.port, err)
	}

	grpcServer := grpc.NewServer()

	// autogenerated by protoc
	order.RegisterOrderServer(grpcServer, a)

	// enable reflection to make grpcurl
	if config.GetEnv() == "development" {
		reflection.Register(grpcServer)
	}

	if err := grpcServer.Serve(listen); err != nil {
		log.Fatalf("failed to serve grpc on port")
	}
}
